baseURL = "https://stivino.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Steven Weber"
enableEmoji = true

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"
 
[params.page]
  lightgallery = false


[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/post/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
[[menu.main]]
    identifier = "gallery"
    post = ""
    name = "Photos"
    url = "/gallery/"
    weight = 1
