baseURL = "https://stivino.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Steven Weber"
enableEmoji = true
typeit = true

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"
 
[params.page]
  lightgallery = false


[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/post/"
    title = "Posts"
    weight = 1
[[menu.main]]
    identifier = "gallery"
    post = ""
    name = "Photos"
    url = "/gallery/"
    weight = 1


[params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/meinAvatar.png"
      title = ""
      subtitle = "Hi! I'm Steven Weber from Saarbrücken, Saarland, Germany."
      typeit = true
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6

  # Social config about the author
  [params.social]
    GitHub = "xxxx"
    Linkedin = "ddd"




